### ISSUE TITLE
Error when testing PUT with django.test.Client

### ISSUE THREAD

**Issue by lifeiscontent** [jgorset/django-respite#38]
Using Django 1.4 and given the following test:

``` python
from django.test import TestCase, Client

class ResourceIndexView(TestCase):
    def test_put_should_update_resource(self):
        """
        A PUT request should result in the resource being updated.
        """
        resource = Resource(name="bob")
        resource.save()
        response = Client().post('/tasks/' + str(task.id), {
            "_method": "PUT",
            'name': "sally"
        })
        self.assertTrue(Resource.objects.all().exists())

```

I receive this error

```
======================================================================
ERROR: test_put_should_update_resource (resources.tests.ResourceIndexView)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/user/Workspace/Git/django-todo/resources/tests.py", line 105, in test_put_should_update_resource
    'description': "sally"
  File "/Users/user/Workspace/Git/django-todo/venv/lib/python2.7/site-packages/django/test/client.py", line 449, in post
    response = super(Client, self).post(path, data=data, content_type=content_type, **extra)
  File "/Users/user/Workspace/Git/django-todo/venv/lib/python2.7/site-packages/django/test/client.py", line 262, in post
    return self.request(**r)
  File "/Users/user/Workspace/Git/django-todo/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 89, in get_response
    response = middleware_method(request)
  File "/Users/user/Workspace/Git/django-todo/venv/lib/python2.7/site-packages/respite/middleware.py", line 25, in process_request
    request._raw_post_data = re.sub(r'_method=(PUT|PATCH|DELETE)&?', '', request.raw_post_data)
  File "/Users/user/Workspace/Git/django-todo/venv/lib/python2.7/site-packages/django/http/__init__.py", line 337, in raw_post_data
    return self.body
  File "/Users/user/Workspace/Git/django-todo/venv/lib/python2.7/site-packages/django/http/__init__.py", line 326, in body
    raise Exception("You cannot access body after reading from request's data stream")
Exception: You cannot access body after reading from request's data stream
```

If I instead use `client.put` the view does not have a populated `request.POST` dictionary. When I output `request.raw_post_data` I get the following unexpected string:

```
'--BoUnDaRyStRiNg\r\nContent-Disposition: form-data; name="name"\r\n\r\nsally\r\n--BoUnDaRyStRiNg--\r\n'
```

Is there an example in this repo of how to use the test client with a `PUT` request or is this truly a bug?

Thanks

**Comment by wiseaidev** [comment]
@GoodPete 
> * Why does `Client().put(data)` need `urlencode` to be called around the dictionary where `Client().post(data)` does not?

I am still having the same thoughts on why on earth `put` and `post` have different encoding types for its content. In my case, the `Client.post` method uses `application/json` for data encoding cause it has `None` inside the serialized data, something like:

```python
self.data = {
    ...
    "name": None
    ...
}
response = self.client.post(
    self.some_reversed_url,
    data=self.data,
    HTTP_AUTHORIZATION=f"Bearer {self.token}",
    content_type="application/json" ,
)
``` 

So, without `content_type="application/json`, the post method won't work. However, doing the same thing with `put` method, it fails and throws a gerbrich error message(I've added a try except block around the update view function to display the error message):

```python
response = self.client.put(
    self.some_reversed_url,
    data=self.data,
    HTTP_AUTHORIZATION=f"Bearer {self.token}",
    content_type="application/json" ,
)
```
```sh
"Cannot r[766 chars]ed"

sometimes the error message is like:

"\xe2\x80[44 chars]D."
```

Not sure what it means. But, after changing the encoding as @jgorset mentioned, it seems to do the trick:

```python
from urllib.parse import urlencode

response = self.client.put(
    self.some_reversed_url,
    data=urlencode(self.data),
    HTTP_AUTHORIZATION=f"Bearer {self.token}",
    content_type="application/x-www-form-urlencoded",
)
```

Thanks @jgorset for your clear explanations, and @GoodPete for pointing that out, without this thread, i might end up spending countless hours on finding the cause of the error and how to resolve it.
